### ISSUE TITLE
buildout takes forever to finish on our conda environments.

### ISSUE THREAD

**Issue by 183amir** [bioidiap/bob.buildout#13]
When using one of the our `idiap` environments, running buildout takes a lot of time.
I think this happens because our conda environment is installed in non-real path (symlink).

**Comment by 183amir** [comment]
I have noticed that this happens in our conda-forge builds too, in our docker images: https://circleci.com/gh/conda-forge/bob.extension-feedstock/33

**Comment by siebenkopf** [comment]
I have had the same problem. I have traced down the issue, and for me I found that buildout always checks the whole current directory for files in the package using ``find_package``, i.e., here:
https://github.com/bioidiap/bob.extension/blob/master/setup.py#L30
Particularly, when you have a large directory inside (which might be a symlink to a network drive), it will scan through the whole directory.

In fact, I have developed a new version of ``find_package`` inside `bob.extension.utils``:
https://github.com/bioidiap/bob.extension/blob/master/bob/extension/utils.py#L369
which I use for example here:
https://github.com/bioidiap/bob.bio.base/blob/master/setup.py#L39

Unfortunately, you cannot use this script to develop ``bob.extension`` -- as it is inside ``bob.extension``. However, you can write a copy of this script into the ``setup.py`` of ``bob.extension`` -- just to see if it helps.

**Comment by siebenkopf** [comment]
The real issue is in the implementation of the original ``find_packages`` function of ``setuptools``. When they scan for package candidates, they **explicitly** include soft links in their search:
https://github.com/pypa/setuptools/blob/master/setuptools/__init__.py#L84
by setting ``followlinks=True`` in ``os.walk``:
https://docs.python.org/2/library/os.html#os.walk

**Comment by anjos** [comment]
That effect happened to me when there were symlinks installed in the local package. Are you saying it is doing this for all installed packages?

**Comment by anjos** [comment]
I ran the buildout with a graphical profiler. The culprit is: `zc.buildout.buildout._dir_hash`. This function is trying to hash **all** files in the `sites-package` directory, recursively with a beautiful `os.walk`. This takes time in a network drive. The total time is proportional to the amount of packages installed on the environment. The fact it is a Conda environment does not play a role. Any large enough environment will have the same issues.

It will do this for every package that it does not find locally. So, having more local checkouts will **not** necessarily help as any other missing dependence (e.g. `six` or `numpy`), will trigger a scan. After the first scan is completed, subsequent calls to `_dir_hash` are cached. Apparently, it is already as efficient as it can be.

**Comment by anjos** [comment]
Note: In that particular use of `os.walk`, the parameter `followlinks` is set to its default, i.e., `False`.

**Comment by 183amir** [comment]
This happens also when only minimal packages are installed:
```
    blas:            1.1-openblas                  conda-forge
    bob.extension:   2.2.1-py27_0                  local      
    boost:           1.61.0-py27_1                 conda-forge
    bzip2:           1.0.6-3                       defaults   
    ca-certificates: 2016.2.28-0                   conda-forge
    cmake:           3.5.0-5                       conda-forge
    curl:            7.49.1-0                      conda-forge
    expat:           2.1.0-1                       conda-forge
    freetype:        2.6.3-1                       conda-forge
    icu:             56.1-4                        conda-forge
    jsoncpp:         0.10.6-1                      conda-forge
    libarchive:      3.2.1-2                       conda-forge
    libblitz:        0.10-0                        conda-forge
    libgfortran:     3.0.0-1                       defaults   
    libiconv:        1.14-2                        conda-forge
    libpng:          1.6.23-0                      conda-forge
    ncurses:         5.9-7                         conda-forge
    nose:            1.3.7-py27_0                  conda-forge
    numpy:           1.11.1-py27_blas_openblas_200 conda-forge [blas_openblas]
    openblas:        0.2.18-3                      conda-forge
    openssl:         1.0.2h-0                      conda-forge
    pip:             8.1.2-py27_0                  conda-forge
    pkg-config:      0.28-1                        conda-forge
    python:          2.7.12-1                      defaults   
    readline:        6.2-0                         conda-forge
    setuptools:      23.0.0-py27_0                 conda-forge
    sqlite:          3.13.0-1                      conda-forge
    tk:              8.5.18-0                      defaults   
    wheel:           0.29.0-py27_0                 conda-forge
    xz:              5.2.2-0                       conda-forge
    zlib:            1.2.8-3                       conda-forge
```
You can see that this build has taken 30 minutes but it used to run in just 5 minutes.
The difference is this:
```diff
   - bob_dependecy_graph.py --help
-  - nosetests -sv bob.extension --exclude=test_cflags_other --exclude=test_extensions
+  - nosetests -sv bob.extension
```
